include: "rules/common.smk"

##### Target Rules #####

# define rules that don't need to be run on a compute node.
# i.e. those that can be run locally.
localrules: all, echo_RG_fixed, genome_faidx, genome_dict, make_scaff_group_interval_lists, make_chromo_interval_lists, make_scatter_interval_lists,
# other local rules
# combine_bcftools_stats, gatk3_register, species_sample_lists, get_genome_length, get_ave_depths


rule all:
    input:
        "results/plink/pca/aut-bisnps-no5indel-pca",
        "results/plink/phylip/aut-bisnps-no5indel",

        #"results/admixture/test_k/aut-snps-0.05-pruned.cv5.error"
        #"results/admixture/aut-snps-0.05-pruned-pca.10.Q"
        
        #expand("results/inbreeding/het/{s}-het-perc.txt", s=sample_list),
        #"results/inbreeding/het/combined-het-percents.tsv",
        
        
        #mapping outputs
        #expand("results/mapping/mkdup/mkdup-{s}.bam", s=sample_list), #mapping final output
        #expand("results/mapping/gatk-rmdup/{s}.bam", s=sample_list), #mapping rmdup final output

        #calling outputs 
        #expand("results/calling/interval_lists/{scaff_group}.list", scaff_group=unique_scaff_groups),
        #expand("results/calling/interval_lists/{chromo}.list", chromo=unique_chromosomes),
        #expand("results/calling/vcf_sections/{sgc}/{scat}.vcf.gz", sgc=sg_or_chrom, scat=unique_scats),
        #expand("results/calling/vcf_sections/{sgc}.vcf.gz", sgc=sg_or_chrom),
        #expand("results/calling/genomics_db/{sgc}", sgc=sg_or_chrom), #calling intermediate output
        #expand("results/calling/gvcf/{s}.{ext}", s=sample, ext = ["g.vcf.gz", "g.vcf.gz.tbi"]), #calling intermediate output
        #expand("results/vcf_sections/{sgc}.{ext}", sgc=sg_or_chrom, ext = ["vcf.gz", "vcf.gz.tbi"]), #calling intermediate output
        #expand("results/scatter_config/scatters_{bs}.tsv", bs=binsize), #generate scatters file from scatter_intervals_file
        #expand("results/calling/corrected_missing_vcf_sect/{sgc}.vcf.gz", sgc=sg_or_chrom), 
        #expand("results/calling/corrected_missing_vcf_sect/all_callable_sites/{sgc}.vcf.gz", sgc=sg_or_chrom),
        
        #hardfiltering outputs
        #"results/bcf/all.bcf", 
        #"results/bcf/all.bcf.csi", 
        #"results/bcf/all-filtered.bcf",
        #"results/bcf/aut-bisnps.bcf",
        #"results/bcf/aut-bisnps-no5indel.bcf",
        #"results/bcf/all_callable_sites/all_callable_sites.bcf",
        #"results/bcf/all_callable_sites/aut_bisnps_all_callable_sites.bcf",
        #expand("results/bcf/{b}-aut-bisnps-maf-0.05.bcf", b=bcfsubsamp),
        #"results/bcf/filt_biallelic_maf_0.05/main.bcf"

        #PSMC outputs
        #expand("results/psmc/remove-sex-bams/aut_{s}.bam", s=sample_list),
        #expand("results/psmc/psmc-consensus-sequence/{s}.fq.gz", s=sample_list)
        #expand("results/psmc/psmcfa/{s}.psmcfa", s=sample_list)
        #expand("results/psmc/run-psmc/{s}.psmc", s=sample_list),
        #expand("results/psmc/psmc-plot/{subsamp}/{subsamp}", subsamp=subsamp),

        #hpsmc outputs
        #expand("results/hpsmc/haploidize_bam_sect/{s}/{chrom}_haploidized.fa", s=sample_list, chrom=unique_chromosomes)
        #expand("results/hpsmc/haploidized_bam/{hp}_haploidized.fa", hp=hpsmcpops),
        #expand("results/hpsmc/psmcfa-from-2-fastas/{p1}---x---{p2}.psmcfa", p1=pop1, p2=pop2),
        #expand("results/hpsmc/run-hpsmc/{p1}---x---{p2}.psmc", p1=pop1, p2=pop2),
        #expand("results/hpsmc/hpsmc-plot/{p1}---x---{p2}", p1=pop1, p2=pop2),
        #"results/hpsmc/split-time-sim/w_fk_boulder---x---steelman/w_fk_boulder---x---steelman",

        #plink outputs
        #expand("results/plink/allele-freq/pop-counts/aut-snps-{maf}", maf=mafs),
        #expand("results/plink/pca/aut-snps-{maf}-ld-pruned-pca", maf=mafs),
        #"results/plink/pw-fst-all/fst-all", 
        #"results/plink/pw-fst-snps-0.05/fst-snps-0.05",
        #expand("results/plink/pca/aut-snps-{maf}-pca", maf=mafs),

        #qc outputs
        #expand("results/qc/samtools_stats/{s}.txt", s=sample_list),
        #expand("results/qc/bcftools_stats/all-{fc}.txt", fc=["ALL", "PASS", "FAIL"],),
        #expand("results/qc/bcftools_stats/all-pass-maf-{maf}.txt", maf=mafs,),
        #expand("results/qc/bcftools_stats/all-pass-maf-{maf}.txt", maf=config["bqsr_maf"], bq=[str(x) for x in range(0, int(config["bqsr_rounds"])+1)]),
        #expand("results/qc/coverage-depth/{s}.txt", s=sample_list),
        #"results/qc/coverage-depth/avg-count/above-10.txt",
        #"results/qc/coverage-depth/avg-count/avg-depth.txt",

        #installing flagfiles 
        #"results/flags/chromcompare_installed",
        #"results/flags/pcangsd_installed",

        #misc outputs
        #expand("results/roh/allele-freq/snps-maf-0.05/{pop}-freqs.tabs.gz", pop=population),
        #expand("results/roh/snps-maf-0.05/{pop}-roh.txt", pop=population)
        #expand("results/angsd_bams/overlap_clipped/{s}.bam", s=sample_list), #angsd-bams output
        #expand("results/angsd_bams/echo-RG-fixed/{s}.txt", s=sample_list), #troubleshooting RG errors
        


##### Modules #####

include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/angsd-ready-bams.smk"
include: "rules/calling.smk"
include: "rules/hardfilter.smk"
include: "rules/psmc.smk"
include: "rules/hpsmc.smk"
include: "rules/qc.smk"
include: "rules/destination-rules.smk"
include: "rules/plink.smk"
include: "rules/inbreeding.smk"
include: "rules/tree.smk"
include: "rules/admixture.smk"
#include: "rules/archive.smk"
#include: "rules/annotation.smk"
#include: "rules/downsample.smk"
#include: "rules/force-call-vcf.smk"