# path to the genome (not used in workflow, but we could have...)
genome_path: "resources/genome/OmykA.fasta"

# path to files needed from config
sample_info: "config/sample-info.tsv"
chromosomes: "config/chromosomes.tsv"
scaffold_groups: "config/scaffold_groups.tsv"
scatter_intervals_file: "results/scatter_config/scatters_1200000.tsv"
replace_RG: "config/replace-RG.tsv"
psmc_info: "config/psmc-info.tsv"


# if you don't want to produce indel-realigned BAMs, set the
# following to False.  It will still make overlap_clipped bams
#do_indel_realignment: False

# the following must be a list, even if it is just one element
maf_cutoffs: [0.05]
binsize: [1200000, 600000] #desired max length for each scatter in the scatter_intervals_file

#if you want to downsample from your bams,
#uncomment and specify the downsample depth
#downsample_bams:
  #depths: []

#this is the default value for the first GenomicsDBImport run.
#If you want to change it, you should typically change it
#on the command line. 
#genomics_db_import_num: 0

# eric modified this to be able to easily handle genomes of non-model
# organisms that are not yet on enseml, etc.
#eric modified this to be able to easily handle genomes of non-model
#organisms that are not yet on enseml, etc.
ref:
  #name of species and genome version, with underscores for spaces
  species_name: "Oncorhynchus_mykiss"
  genome_version_name: "USDA_OmykA_1.1"
  #the URL where this can be downloaded, if public and easy to
  #get with wget.  If not, then you should hand-download
  #genome.fasta and genome.gff or genome.gtf
  genome_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/013/265/735/GCF_013265735.2_USDA_OmykA_1.1/GCF_013265735.2_USDA_OmykA_1.1_genomic.fna.gz"
  #if there is a GFF or GTF file, they have to have a .gff or
  #.gtf extension. This is where you put the URL for it
#  gff_or_gtf_url: ""

#parameters to be used for different rules/programs
#the adapter sequences are for the NovaSeq X listed in the Novogene data report
#variant hard filtering is based on GATK best practices
params:
  fastp:
    adapter_sequence1: "ATCGGAAGAGCACACGTCTGAACTCCAGTCACGGATGACTATCTCGTATGCCGTCTTCTGCTTG"
    adapter_sequence2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT"
    other_options:
      - "--detect_adapter_for_pe"
      - "--cut_right" 
      - "--cut_right_window_size 4"
      - "--cut_right_mean_quality 20"
  picard:
    MarkDuplicates: " --TAGGING_POLICY All --CREATE_INDEX --TMP_DIR results/snake-tmp "
  gatk:
    # the default for haplotype caller is to require very high base quality scores
    # because BQSR on non-model organisms doesn't work for crap, and Nina's group
    # found it better to just require high base quality scores. - Eric
    HaplotypeCaller: " --min-base-quality-score 33 --minimum-mapping-quality 20 "
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
    VariantFiltration:
      indels:
        - ' -filter "QD < 2.0" --filter-name "QD2" '
        - ' -filter "QUAL < 30.0" --filter-name "QUAL30" '
        - ' -filter "FS > 200.0" --filter-name "FS200" '
        - ' -filter "ReadPosRankSum < -20.0" --filter-name "ReadPosRankSum-20" '
      snps:
        - ' -filter "QD < 2.0" --filter-name "QD2" '
        - ' -filter "QUAL < 30.0" --filter-name "QUAL30" '
        - ' -filter "SOR > 3.0" --filter-name "SOR3" '
        - ' -filter "FS > 60.0" --filter-name "FS60" '
        - ' -filter "MQ < 40.0" --filter-name "MQ40" '
        - ' -filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5" '
        - ' -filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8" '

#### SETTING INSTALL SECTIONS #####
## I forked the most up to date version of the repository for the packages I was using
# Linking it to my fork makes it reproducible in case the main page is updated and commands are depreciated in the future
# The version hash refers to the commit version you want to pull - github is so cool!
pcangsd:
  url: https://github.com/Rosemeis/pcangsd.git
  version: 982ba6f7b2d2f015aa64b600a524d842b3615dad
chromcompare:
    url: https://github.com/Paleogenomics/Chrom-Compare.git
    version: e38bc94d8bca18347e6c4c20582850e03cbd0cfd
hpsmc:
    url: https://github.com/jacahill/hPSMC.git
    version: f69f899bb924637611d818f2bb35c574837420f3 #this is here just for the version of hPSMC scripts I used


#### Setting the subsample wildcards for PSMC ####
# I actually don't use this right now but might use it later 
# or use a similar structure for the hPSMC subsets
#psmc:
#  lineage:
#    sample_subsets:
#      all:
#        path: config/sample_subsets/all-fish.txt
#      crct-blue:
#        path: config/sample_subsets/blue-fish.txt
#      crct-green:
#        path: config/sample_subsets/green-fish.txt
#      crct-both:
#        path: config/sample_subsets/crct-fish.txt
#      outgroups:
#        path: config/sample_subsets/outgroup-fish.txt
  #population:
  #  sample_subsets:
  #    all:
  #      path: config/sample_subsets/all-fish.txt
hpsmc-test:
    bams: config/hpsmc-bams.tsv
    pwcomps: config/hpsmc-pwcomps.tsv
    chroms: config/hpsmc-chroms.tsv
bcf:
  sample_subsets:
    co-lineages:
      path: config/sample_subsets/co-lineages.txt
    o-virginialis:
      path: config/sample_subsets/o-virginialis.txt